# Generated by Django 3.2.16 on 2024-09-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240728_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Картинка у публикации'),
        ),
    ]
